# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(max_length=200)),
            ],
        ),
    ]
